---
title: Skills
hero_image: images/banner.png
description: GBICi5-Scratch-1-Skills description
version: 4
listed: false
copyedit: false
last_tested: '2019-08-14'
steps:
- title: Skills Link to Careers in Computing
